AWSTemplateFormatVersion: "2010-09-09"
Description: "Web server"

Parameters:
  InstanceType:
    Description: "Enter t2.micro or t3.micro. Default is t2.micro."
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - "t2.micro"
      - "t3.micro"

Resources:
  WebServerEC2LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: "WebServerTemplate"
      LaunchTemplateData:
        ImageId: "ami-00e801948462f718a"
        InstanceType: !Ref InstanceType
        UserData:
          Fn::Base64: |
            #!/bin/bash
            set -xe

            yum update -y
            yum install -y httpd

            systemctl start httpd
            systemctl enable httpd

            TOKEN=$(curl -sS -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            PUBLIC_IP=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4)
            INSTANCE_ID=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)

            echo "<h1>Hello from EC2</h1>" > /var/www/html/index.html
            echo "<h2>Instance ID: $INSTANCE_ID</h2>" >> /var/www/html/index.html
            echo "<h2>Public IPv4: $PUBLIC_IP</h2>" >> /var/www/html/index.html

  WebServerASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AutoScalingGroupName: "WebServerASG-Demo"
      LaunchTemplate:
        LaunchTemplateId: !Ref WebServerEC2LaunchTemplate
        Version: !GetAtt WebServerEC2LaunchTemplate.LatestVersionNumber
      DesiredCapacity: "2"
      MaxSize: "2"
      MinSize: "1"
      VPCZoneIdentifier:
        - "subnet-09856c9b0e1b0e0b8"
        - "subnet-0baa48aaba98c873f"
